src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

import api.views as views

app_name = "api"
router = routers.DefaultRouter()
router.register("categories", views.CategoryViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-redoc"),
    path("", include(router.urls)),
    path("auth/", include("djoser.urls.jwt")),
    path("products/", views.ProductListView.as_view(), name="products_list"),
    path("products/create", views.ProductCreateView.as_view(), name="products_create"),
    path("products/<int:pk>/", views.ProductDetailsView.as_view(), name="products_details"),
    path("products/<int:pk>/update", views.ProductUpdateView.as_view(), name="products_update"),
    path("products/<int:pk>/delete", views.ProductDeleteView.as_view(), name="products_delete"),
]

src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config.settings import dev as settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("", include("shop.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from main.views import (UserActivationView, UserRegistrationView, index,
                        user_login, user_logout)

app_name = 'main'


urlpatterns = [
    path("", index, name="index"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("activate/<int:pk>/<str:token>/", UserActivationView.as_view(), name="activate"),
]

src/shop/urls.py
from django.urls import path

from shop.views import cart, get_products

app_name = "shop"

urlpatterns = [
    path("", get_products, name="get_products"),
    path("cart/", cart, name="cart"),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Abstract Shop</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
    {% include 'navbar.html' %}
    <br>
    <div class="container">
        {% block content %} Content {% endblock %}
    </div>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <h1>Homepage</h1>
</div>

{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">
            {% load static %}
            AbstractShop
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'shop:get_products' %}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'shop:cart' %}">Cart</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.get_full_name }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:login' %}">Login</a>
                    </li>
                {% endif%}
            </ul>
        </div>
    </div>
</nav>